name: cyoga
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_swiper : ^1.1.6
  flutter_screenutil: ^0.5.2
  flutter_staggered_grid_view: "^0.3.0"
  fluro: "^1.5.1"
  flutter_statusbarcolor: "0.2.3"
  dio: 2.1.4
  cookie_jar: "^1.0.0"
  flutter_easyrefresh: ^1.2.7
  common_utils: ^1.1.1
  flustars: ^0.2.5+1
  rxdart: 0.22.0
  flukit: ^1.0.0
  cached_network_image: ^1.1.3
  url_launcher: ^4.0.1
  fluintl: ^0.1.3
  azlistview: ^0.1.2
  lpinyin: ^1.0.7
  device_info: ^0.4.0+2
  pull_to_refresh: 1.1.6
  fluttertoast: ^3.1.3
  flutter_spinkit: "^2.1.0"
  flutter_html: "^0.10.4"
  provider: ^3.0.1
  video_player: ^0.10.1
  auto_orientation: ^1.0.5
  bot_toast: ^2.1.1
  progress_indicators: ^0.1.4
  logger: ^0.7.0+2
  permission_handler: ^4.0.0
  screen: ^0.0.5
  photo_view: ^0.9.0
  popup_menu: ^1.0.5
  flutter_map: ^0.7.0
  shared_preferences: 0.5.4+8
  package_info: ^0.4.0+12
  ota_update: ^2.2.1
  path_provider: ^1.1.0
  open_file: ^2.0.1+2
  progress_dialog: 1.2.0
  flutter_webview_plugin: 0.3.10+2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/3.0x/
    - images/logo.png
    - images/banner.png
    - images/head_menu_1.png
    - images/head_menu_2.png
    - images/head_menu_3.png
    - images/head_menu_4.png
    - images/head_menu_5.png
    - images/head_menu_6.png
    - images/head_menu_7.png
    - images/head_menu_8.png

    - images/scrollmenu_1.png
    - images/scrollmenu_2.png
    - images/scrollmenu_3.png

    - images/check_in.png
    - images/lottery.png
    - images/new_talent.png
    - images/new_store.png
    - images/new_shop_text.png
    - images/newcomer_text.png
    - images/points_lottery_text.png
    - images/check_in_text.png

    - images/headline_icon.png

    - images/ad_bar.png
    - images/home_near_store.png
    - images/discount_bg.png
    - images/wallet_red.png
    - images/wallet_yellow.png
    - images/see_more_text1.png
    - images/see_more_text2.png

    - images/baobao.png
    - images/huazp.png

    - images/default_avatar.png
    - images/card_coupon.png
    - images/information.png
    - images/referrer.png

    - images/personal_ad.png

    - images/invite_friends.png
    - images/my_fans.png
    - images/income.png
    - images/reward.png

    - images/guide.png
    - images/footprint.png
    - images/about.png
    - images/complaint.png
    - images/customer.png
    - images/problem.png
    - images/clear.png
    - images/sign_out.png

    - images/exchange_btn.png

    - images/poster_content.png

    - images/contact_merchant.png
    - images/call_hotline.png

    - images/flame_ico.png

    - images/store_list_label.png

    - images/order_form.png
    - images/details_description.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
#  fonts:
#      - family:  MyIcons
#        fonts:
#          - asset: fonts/MyFlutterApp.ttf
  fonts:
    - family:  MyIcons
      fonts:
        - asset: fonts/MyFlutterApp.ttf

    - family:  yogaIcons
      fonts:
        - asset: fonts/iconfonty.ttf

    - family:  MyIcons2
      fonts:
        - asset: fonts/iconfont2.ttf

    - family:  IconFont
      fonts:
        - asset: fonts/iconfont.ttf
